---
title: "Converting File Types"
author: "Shaun Truelove"
date: "2025-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### 2. Convert Data Between Formats

The package provides helper functions to convert data between hub format and various forecasting package formats:

#### Hub ↔ Fable/tsibble

Convert hub data to tsibble for fable modeling

```{r, include=TRUE}
hub_data <- data.frame(
  date = seq.Date(as.Date("2023-01-01"), by = "week", length.out = 20),
  location = "US",
  value = rnorm(20, 100, 10)
)

# Convert to tsibble format
ts_data <- convert_hub_to_tsibble(hub_data)

# Use with fable
library(fable)
library(tsibble)
model <- ts_data %>% 
  model(arima = ARIMA(value))

# Convert fable forecasts back to hub format
forecasts <- model %>% forecast(h = 4)
hub_forecasts <- convert_fable_to_hub(forecasts, location = "US")
```

#### Hub ↔ EpiEstim

```{r, include=TRUE}
# Prepare data for EpiEstim
epiestim_data <- convert_hub_to_epiestim(
  hub_data, 
  location_filter = "US"
)

# Run EpiEstim (example)
library(EpiEstim)
res <- estimate_R(epiestim_data, method = "parametric_si",
                  config = make_config(list(mean_si = 7, std_si = 4.5)))

# Convert results back to hub format
hub_r_estimates <- convert_epiestim_to_hub(res, location = "US")
```

#### Hub ↔ EpiNow2

```{r, include=TRUE}
# Prepare data for EpiNow2
epinow2_data <- convert_hub_to_epinow2(
  hub_data,
  location_filter = "US"
)

# Run EpiNow2 (example)
library(EpiNow2)
res <- epinow(
  reported_cases = epinow2_data,
  generation_time = generation_time_opts(Generation_Time_Opts(...)),
  delays = delay_opts(Delay_Opts(...))
)

# Convert results back to hub format
hub_forecasts <- convert_epinow2_to_hub(res, location = "US")
```
